VANTA.WAVES({
  shininess: 20,
  el: ".background",
  color: "#0C0A09",
  mouseControls: true,
  touchControls: true,
  gyroControls: false,
  minHeight: 200.0,
  minWidth: 200.0,
  scale: 1.0,
  scaleMobile: 1.0,
  waveSpeed: 0.1,
  waveHeight: 5,
  zoom: 1.8,
});
